<?php

return
    [
        'premissions' =>
            [
                'roles' => 'الادوار و التحكمات',
                'addRole' => 'اضافة دور جديد',
                'editRole' => 'تعديل الدور',
                'deleteRole' => 'حذف الدور',
                'employee' => 'الموظفين',
                'addEmployee' => 'اضافة موظف',
                'editEmployee' => 'تعديل موظف',
                'deleteEmployee' => 'حذف موظف',
                'users' => 'المستخدمين',
                'addUser' => 'اضافة مستخدم',
                'editUser' => 'تعديل مستخدم',
                'deleteUser' => 'حذف مستخدم',
                'admins' => 'المشرفين',
                'addAdmin' => 'اضافة مشرف',
                'editAdmin' => 'تعديل مشرف',
                'deleteAdmin' => 'حذف مشرف',
                'setting_change' => 'الاعدادت العامة',
                'sliders' => 'الصور الاعلانية',
                'addSlider' => 'اضافة صورة اعلانيه',
                'editSlider' => 'حذف صورة اعلانيه',
                'deleteSlider' => 'تعديل صورة اعلانيه',
                'categories' => 'الاقسام',
                'addCategory' => 'اضافة قسم',
                'deleteCategory' => 'حذف قسم',
                'editCategory' => 'تعديل قسم',
                'Chopping' => 'طرق التقطيع',
                'addChopping' => 'اضافة طرق التقطيع',
                'editChopping' => 'تعديل طرق التقطيع',
                'deleteChopping' => 'حذف طرق التقطيع',
                'Wrapping' => 'طرق التغليف',
                'addWrapping' => 'اضافة طرق التغليف',
                'editWrapping' => 'تعديل طرق التغليف',
                'deleteWrapping' => 'حذف طرق التغليف',
                'products' => 'المنتجات',
                'addProduct' => 'اضافة منتج',
                'deleteProduct' => 'حذف منتج',
                'editProduct' => 'تعديل منتج',
                'about' => 'معلومات عنا',
                'contact' => 'اتصل بنا',
                'terms' => 'الشروط و الاحكام',
                'notifications' => 'الاشعارات',
                'whoUs' => 'من نحن'
            ]
    ];
