<?php

return
    [
        'premissions' =>
            [
                'roles' => 'roles and controls',
                'addRole' => 'Add a new role',
                'editRole' => 'Edit Role',
                'deleteRole' => 'Delete role',
                'employee' => 'employees',
                'addEmployee' => 'Add employee',
                'editEmployee' => 'Edit Employee',
                'deleteEmployee' => 'Delete employee',
                'users' => 'users',
                'addUser' => 'Add User',
                'editUser' => 'Edit User',
                'deleteUser' => 'Delete User',
                'admins' => 'admins',
                'addAdmin' => 'Add Admin',
                'editAdmin' => 'edit admin',
                'deleteAdmin' => 'Delete Admin',
                'setting_change' => 'General Settings',
                'sliders' => 'advertising images',
                'addSlider' => 'Add an advertising image',
                'editSlider' => 'Delete ad image',
                'deleteSlider' => 'Edit ad image',
                'categories' => 'sections',
                'addCategory' => 'Add Category',
                'deleteCategory' => 'Delete Category',
                'editCategory' => 'Edit Category',
                'Chopping' => 'Chopping methods',
                'addChopping' => 'Add chopping methods',
                'editChopping' => 'Edit Chopping Methods',
                'deleteChopping' => 'Delete Chopping Methods',
                'Wrapping' => 'Wrapping methods',
                'addWrapping' => 'Add wrapping methods',
                'editWrapping' => 'Edit Wrapping Methods',
                'deleteWrapping' => 'Delete wrapping methods',
                'products' => 'products',
                'addProduct' => 'Add Product',
                'deleteProduct' => 'Delete Product',
                'editProduct' => 'Edit Product',
                'orders' => 'orders',
                'changeStatus' => 'Change order status',
                'deleteOrder' => 'Delete order',
                'about' => 'about us',
                'contact' => 'contact us',
                'terms' => 'Terms and Conditions',
                'notifications' => 'notifications',
                'whoUs' => 'Who we are'
            ]
    ];
